server:
  port: 8050
spring:
  application:
    name: microservice-file-upload
  http:
    multipart:
      max-file-size: 2000Mb
      max-request-size: 2500Mb

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/,http://peer2:8882/eureka/,http://peer1:8881/eureka/,http://peer3:8883/eureka/
  instance:
    prefer-ip-address: true
    # eureka 显示ip和端口的配置
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}

#ribbon
ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 60000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1

#hystrix
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 60000
