server:
  port: 8000
spring:
  profiles:
    active: dev
  datasource:
    # 驱动不同 mysql 5  com.mysql.jdbc.Driver
    #         mysql 8  com.mysql.cj.jdbc.Driver、需要增加时区的配置serverTimezone=GMT%2B8
    url: jdbc:mysql://localhost:3306/mybatis_plus?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
#logging:
#  level:
#    root: INFO
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

global-config:
  db-config:
    logic-delete-value: 1
    logic-not-delete-value: 0
